-- 코드를 작성해주세요
SELECT
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    S.SIZE - E.SIZE_OF_COLONY as YEAR_DEV,
    E.ID
FROM
    ECOLI_DATA AS E
JOIN
    (SELECT 
        YEAR(E2.DIFFERENTIATION_DATE) AS YEAR,
        MAX(E2.SIZE_OF_COLONY) AS SIZE
     FROM
        ECOLI_DATA AS E2
     GROUP BY
        YEAR
    ) AS S
ON S.YEAR = YEAR(DIFFERENTIATION_DATE)
ORDER BY
    YEAR ASC,
    YEAR_DEV ASC